%% -*- erlang-mode -*-
case os:getenv("ERLANG_ROCKSDB_OPTS") of
    false ->
        true = os:putenv("ERLANG_ROCKSDB_OPTS", "-DWITH_BUNDLE_LZ4=ON");
    _ ->
        %% If manually set, we assume it's throught through
        skip
end.
case os:getenv("DEBUG") of
    "true" ->
	Opts = proplists:get_value(erl_opts, CONFIG, []),
	lists:keystore(erl_opts, 1, CONFIG,
		       [{d,'DEBUG'} | Opts -- [{d,'DEBUG'}]]);
    _ ->
	CONFIG
end.
