version: 2.1

executors:
  aebuilder:
    name: aebuilder-<< matrix.otp >>
    matrix:
      parameters:
        otp: ["otp23", "otp24"]
    docker:
      - image: aeternity/builder:bionic-<< matrix.otp >>
        user: builder
    environment:
      ERLANG_ROCKSDB_BUILDOPTS: "-j2"

jobs:
  - build:
      name: build_and_test-<< matrix.otp >>
      executor: aebuilder-<< matrix.otp >>
      matrix:
        parameters:
          otp: ["otp23", "otp24"]
      steps:
        - checkout
        - run: make test
        - store_artifacts:
            path: _build/test/logs

workflows:
  build_and_test:
    jobs:
      - build_and_test-otp23
      - build_and_test-otp24
